---
root: true

env:
  browser: true
  commonjs: true
  es2021: true

extends: eslint:recommended

parserOptions:
  ecmaVersion: latest

rules:
  comma-dangle: ['error', 'never']
  max-len:
    - 'error'
    - code: 80
  newline-before-return: 'error'
  no-console: 'off'
  semi: ['error', 'never']
