---
parserOptions:
  sourceType: module

parser: 'babel-eslint'

env:
  node: true

extends:
  - standard
  - prettier
  - prettier/standard

plugins:
  - prettier

rules:
  comma-dangle: ['error', 'never']
  max-len:
    - 'error'
    - code: 80
  newline-before-return: 'error'
  no-console: 'off'
  promise/catch-or-return: 'error'
  semi: ['error', 'never']
